/**
 * Published.toml reader / writer.
 *
 * Format (generated by the `sui` CLI):
 *
 *   # comment block
 *
 *   [published.<env>]
 *   chain-id           = "4c78adac"
 *   published-at       = "0x..."
 *   original-id        = "0x..."
 *   version            = 1
 *   toolchain-version  = "1.69.1"
 *   build-config       = { flavor = "sui", edition = "2024" }
 *   upgrade-capability = "0x..."
 *
 * Parsing/writing is delegated to smol-toml to keep this module concise.
 */

import * as fs from 'node:fs/promises'
import * as path from 'node:path'
import { parse, stringify } from 'smol-toml'
import { z } from 'zod/v4'
import {
  publishedEntrySchema,
  publishedTomlSchema,
} from './schemas/published-toml.ts'
import type { PublishedEntry } from './types.ts'

export const PUBLISHED_TOML = 'Published.toml'

type PublishedTomlDoc = z.infer<typeof publishedTomlSchema>

function parseTomlWithSchema(rawToml: string): PublishedTomlDoc {
  const parsed = parse(rawToml)
  const result = publishedTomlSchema.safeParse(parsed)
  if (!result.success) {
    throw new Error(
      `Failed to validate Published.toml structure: ${z.prettifyError(result.error)}`
    )
  }
  return result.data as PublishedTomlDoc
}

function fromTomlEntry(entry: Record<string, unknown>): PublishedEntry {
  const result = publishedEntrySchema.safeParse(entry)
  if (!result.success) {
    throw new Error(
      `Invalid Published.toml entry: ${z.prettifyError(result.error)}`
    )
  }

  const normalized = result.data
  const buildConfigRaw = normalized['build-config']
  const buildConfig =
    buildConfigRaw && typeof buildConfigRaw === 'object'
      ? stringify(buildConfigRaw as Record<string, unknown>).trim()
      : '{}'

  const version =
    typeof normalized.version === 'bigint'
      ? Number(normalized.version)
      : Number(normalized.version)

  return {
    chainId: normalized['chain-id'],
    publishedAt: normalized['published-at'],
    originalId: normalized['original-id'],
    version,
    toolchainVersion: normalized['toolchain-version'],
    buildConfig,
    upgradeCapability: normalized['upgrade-capability'],
  }
}

// ─── Public API ────────────────────────────────────────────────────────────

export interface ParsedToml {
  raw: PublishedTomlDoc
  entries: Map<string, PublishedEntry>
}

export async function readPublishedToml(
  dir: string
): Promise<ParsedToml | null> {
  const filePath = path.join(dir, PUBLISHED_TOML)
  let rawToml: string
  try {
    rawToml = await fs.readFile(filePath, 'utf8')
  } catch {
    return null
  }

  let doc: PublishedTomlDoc
  try {
    doc = parseTomlWithSchema(rawToml)
  } catch (error) {
    throw new Error(`Failed to parse Published.toml: ${String(error)}`)
  }

  const entries = new Map<string, PublishedEntry>()

  const published = doc.published ?? {}
  for (const [env, value] of Object.entries(published)) {
    if (!value || typeof value !== 'object') continue
    entries.set(env, fromTomlEntry(value as Record<string, unknown>))
  }

  return { raw: doc, entries }
}

export async function writePublishedToml(
  dir: string,
  parsed: ParsedToml
): Promise<void> {
  const filePath = path.join(dir, PUBLISHED_TOML)
  await fs.writeFile(filePath, stringify(parsed.raw), 'utf8')
}

/**
 * Remove one [published.<env>] section if present.
 * Returns true when a section was removed and the file was rewritten.
 */
export async function removePublishedEntry(
  dir: string,
  env: string
): Promise<boolean> {
  const parsed = await readPublishedToml(dir)
  if (!parsed) return false
  if (!parsed.raw.published?.[env]) return false

  const raw: PublishedTomlDoc = {
    ...parsed.raw,
    published: { ...(parsed.raw.published ?? {}) },
  }
  delete raw.published?.[env]

  await writePublishedToml(dir, { raw, entries: parsed.entries })
  return true
}
